application: mckinnon-polymer
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /bower_components
  static_dir: build/defaullt/bower_components
  secure: always

- url: /images
  static_dir: build/defaullt/images
  secure: always

- url: /src
  static_dir: build/defaullt/src
  secure: always

- url: /service-worker.js
  static_files: build/defaullt/service-worker.js
  upload: build/defaullt/service-worker.js
  secure: always

- url: /manifest.json
  static_files: build/defaullt/manifest.json
  upload: build/defaullt/manifest.json
  secure: always

- url: /.*
  static_files: build/defaullt/index.html
  upload: build/defaullt/index.html
  secure: always
